bot:
  name: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_BOT_TOKEN}

server:
  port: 8003
  address: localhost

spring:
  application:
    name: bot

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 45

  client:
    registerWithEureka: true
    fetch-registry: true
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  info:
    git:
      enabled: true
      mode: full
    build:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,metrics
        exclude: health

info:
  application:
    parent:
      groupId: @pom.parent.groupId@
      artifactId: @pom.parent.artifactId@
      version: 0.0.1
    service:
      artifactId: @pom.artifactId@
      version: @pom.version@
      name: @pom.name@
      description: @pom.description@
  build:
    time: @maven.build.timestamp@
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}
  git:
    branch: ${git.branch}
    commit:
      id: ${git.commit.id}
      message: ${git.commit.message.full}
      time: ${git.commit.time}
      user:
        email: ${git.commit.user.email}
        name: ${git.commit.user.name}