server:
  port: 8000
  address: localhost
---
spring:
  profiles:
    default: dev
    active: dev
#    active: prod
---
spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  application:
    name: orchestrator

cache:
  timeout: 5 #minutes
  size: 100

sms:
  url:
    replenish-balance: https://sms.ru/pay.php

testData:
  enabled: true
  usersCount: 5
  requestsCount: 2

logging:
  file:
    name: logs/app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 45
  client:
    registerWithEureka: true
    fetch-registry: true
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

jwt:
  primeAdminLogin: admin
  primeAdminPassword: admin
  primeAdminChatId: 010101
  secret:
    path: keys/keystore.jks
    password: password
    alias: jwtsigning

schedulers:
  zone: "Europe/Moscow"
  report-reminders:
    cron: 0 0 22 * * *

navbar:
  admin:
    - Курсы
      /courses
    - Баланс 
      /balancePage
    - Все студенты 
      /allStudents
    - Запросы на регистрацию
      /joinRequests
    - Вопросы к ревью 
      /questionsAdmin
    - Статистика 
      /statistics
  user:
    - Курсы 
      /courses
    - Написать отчет 
      /report
    - Вопросы к ревью 
      /questions
    - Персональные данные
      /personalData