---
spring:
  config:
    activate:
      on-profile: prod
---
spring:
  datasource:
    password: ${ORCHESTRATOR_DB_PASSWORD}
    username: ${ORCHESTRATOR_DB_USERNAME}
    url: ${ORCHESTRATOR_DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    generate-ddl: true