---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5430/orchestrator-db
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    generate-ddl: true