server:
  port: 8000
  address: localhost

spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  application:
    name: orchestrator

cache:
  timeout: 5 #minutes
  size: 100

sms:
  url:
    replenish-balance: https://sms.ru/pay.php


logging:
  file:
    name: logs/app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 45
  client:
    registerWithEureka: true
    fetch-registry: true
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

