server:
  port: 8001
  address: localhost

spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  application:
    name: notification

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 45

  client:
    registerWithEureka: true
    fetch-registry: true
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka