server:
  port: 8001
  address: localhost

sms:
  url: https://sms.ru
  api:
    id: ${SMS_API_ID}

---
spring:
  profiles:
    default: dev
    active: dev
#    active: prod
---
spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  application:
    name: notification
  mail:
    protocol: smtps
    host: smtp.yandex.ru
    port: 465
    username: ${MAIL_USER_NAME}
    password: ${MAIL_PASSWORD}

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 45

  client:
    registerWithEureka: true
    fetch-registry: true
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka